# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-03-28 09:17
from __future__ import unicode_literals

import blog.storage
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, default='#', null=True, verbose_name='链接')),
                ('cover', models.ImageField(upload_to=blog.storage.PathAndRename('cover'), verbose_name='封面')),
                ('type', models.CharField(choices=[('l', '星辰大海'), ('j', '碎碎念'), ('w', '旅行')], default='l', max_length=1, verbose_name='类型')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('excerpt', models.TextField(verbose_name='摘要')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='修改时间')),
                ('published', models.BooleanField(default=True, verbose_name='发布')),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='开启评论')),
                ('publish_time', models.DateTimeField(null=True, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='标签用英文逗号隔开', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-is_top', '-update_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=16, verbose_name='评论用户名')),
                ('c_photo', models.CharField(max_length=256, verbose_name='评论这头像')),
                ('c_content', models.TextField(max_length=512, verbose_name='评论内容')),
                ('zan', models.IntegerField(default=0, verbose_name='点赞数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('article_id', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='关联文章')),
                ('comment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment', verbose_name='自关联')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='名称')),
                ('link', models.URLField(default='', verbose_name='链接')),
                ('cover', models.ImageField(blank=True, upload_to=blog.storage.PathAndRename('link'), verbose_name='头像')),
                ('desc', models.TextField(default='未添加描述', verbose_name='描述')),
                ('position', models.SmallIntegerField(default=1, verbose_name='位置')),
                ('active', models.BooleanField(default=True, verbose_name='激活')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='名称')),
                ('url', models.CharField(max_length=50, unique=True, verbose_name='地址')),
                ('cover', models.ImageField(blank=True, upload_to=blog.storage.PathAndRename('social'), verbose_name='图标')),
                ('position', models.SmallIntegerField(default=1, verbose_name='位置')),
            ],
            options={
                'verbose_name': '社交网站',
                'verbose_name_plural': '社交网站',
                'ordering': ['-position'],
            },
        ),
    ]
