# Generated by Django 2.0.5 on 2020-03-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article_id',
            field=models.OneToOneField(default=0, on_delete=None, to='blog.Article', verbose_name='关联文章'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.ForeignKey(default=0, null=True, on_delete=None, to='blog.Comment', verbose_name='自关联'),
        ),
    ]
