# Generated by Django 2.0.5 on 2020-03-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200328_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='p_id',
            field=models.IntegerField(default=1, verbose_name='顶级评论'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.OneToOneField(default=0, on_delete=None, to='blog.Comment', verbose_name='自关联'),
        ),
    ]
