# Generated by Django 2.0.5 on 2020-03-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200329_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='p_id',
            field=models.IntegerField(default=0, verbose_name='顶级评论'),
        ),
    ]
