# Generated by Django 2.0.5 on 2020-03-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200329_0009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
